export const MEETING_OPERATION_ERROR_KIND = 'meeting-operation-error' as const;

export const meetingOperationErrorHandling = {
  result: 'result',
  toast: 'toast',
} as const;

export type MeetingOperationErrorHandling =
  (typeof meetingOperationErrorHandling)[keyof typeof meetingOperationErrorHandling];

export const meetingOperationErrorReason = {
  availability: 'availability',
  deleted: 'deleted',
  insufficientPermissions: 'insufficient-permissions',
  internal: 'internal',
  validation: 'validation',
} as const;

export type MeetingOperationErrorReason =
  (typeof meetingOperationErrorReason)[keyof typeof meetingOperationErrorReason];

export const meetingOperationMessageSource = {
  connectivity: 'connectivity',
  meeting: 'meeting',
  rcVideo: 'rc-video',
} as const;

export type MeetingOperationMessageSource =
  (typeof meetingOperationMessageSource)[keyof typeof meetingOperationMessageSource];

export const meetingOperationMessageKey = {
  durationIncorrect: 'durationIncorrect',
  emptyTopic: 'emptyTopic',
  insufficientPermissions: 'insufficientPermissions',
  internalError: 'internalError',
  invalidMeetingInfo: 'invalidMeetingInfo',
  meetingIsDeleted: 'meetingIsDeleted',
  noPassword: 'noPassword',
  offline: 'offline',
} as const;

export type MeetingOperationMessageKey =
  (typeof meetingOperationMessageKey)[keyof typeof meetingOperationMessageKey];

export type MeetingOperationMessageParams = Record<string, number | string>;

/** Serializable notification copy or a descriptor localized by the UI owner. */
export type MeetingOperationMessage =
  | {
      message: string;
    }
  | {
      messageKey: MeetingOperationMessageKey;
      messageParams?: MeetingOperationMessageParams;
      messageSource: MeetingOperationMessageSource;
    };

export type MeetingOperationNotification = MeetingOperationMessage & {
  level: 'danger' | 'warning';
};

export type MeetingOperationTranslator = (
  messageKey: MeetingOperationMessageKey,
  messageParams?: MeetingOperationMessageParams,
) => string;

/** Resolves both legacy raw messages and caller-localized notification descriptors. */
export const resolveMeetingOperationNotification = (
  notification: MeetingOperationNotification,
  translate: MeetingOperationTranslator,
) =>
  'message' in notification
    ? notification.message
    : translate(notification.messageKey, notification.messageParams);

/** Serializable failure returned when the initiating client owns error UI. */
export type MeetingOperationErrorResult = {
  kind: typeof MEETING_OPERATION_ERROR_KIND;
  notifications: MeetingOperationNotification[];
  reason: MeetingOperationErrorReason;
};

/** Controls success notification behavior and ownership of operation failures. */
export type MeetingOperationOptions = {
  errorHandling?: MeetingOperationErrorHandling;
  /** Uses the initiating client's locale for content generated by a shared worker. */
  locale?: string;
  /** @deprecated Use `locale`; retained for callers that only localized invitations. */
  invitationLocale?: string;
  isAlertSuccess?: boolean;
};

/** Resolves a serializable caller locale while preserving the legacy invitation option. */
export const getMeetingOperationLocale = (
  options: MeetingOperationOptions | undefined,
  fallbackLocale: string,
) => options?.locale ?? options?.invitationLocale ?? fallbackLocale;

/** Controls lookup error notification behavior and ownership of lookup failures. */
export type MeetingLookupOptions = {
  errorHandling?: MeetingOperationErrorHandling;
  isAlertError?: boolean;
};

/** Controls whether delete failures are shown by the service or returned to the caller. */
export type MeetingDeleteOptions = {
  errorHandling?: MeetingOperationErrorHandling;
};

export type MeetingOperationReturn<
  TOptions extends { errorHandling?: MeetingOperationErrorHandling },
  TResult,
> = TOptions extends { errorHandling: 'result' }
  ? TResult | MeetingOperationErrorResult
  : TResult | null;

export type MeetingLookupReturn<
  TOptions extends { errorHandling?: MeetingOperationErrorHandling },
  TResult,
> = TOptions extends { errorHandling: 'result' }
  ? TResult | MeetingOperationErrorResult
  : TResult;

export type MeetingDeleteReturn<TOptions extends MeetingDeleteOptions> =
  TOptions extends { errorHandling: 'result' }
    ? true | MeetingOperationErrorResult
    : boolean;

export const createMeetingOperationError = (
  reason: MeetingOperationErrorReason,
  notifications: MeetingOperationNotification[],
): MeetingOperationErrorResult => ({
  kind: MEETING_OPERATION_ERROR_KIND,
  notifications,
  reason,
});

export const isMeetingOperationError = (
  value: unknown,
): value is MeetingOperationErrorResult =>
  typeof value === 'object' &&
  value !== null &&
  (value as MeetingOperationErrorResult).kind ===
    MEETING_OPERATION_ERROR_KIND &&
  Array.isArray((value as MeetingOperationErrorResult).notifications);
